# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon-sakabanjiayu.jpg"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🌝"
    subtitle = "The ultimate lie in programming is “It's gonna be done”"
    avatar   = "img/sakabanjiayu.jpeg"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
# [comments]
#     enabled  = true
#     provider = "disqus"
  [comments]
      enabled = true
      provider = "giscus"

      [comments.giscus]
          repo             = "MisenoMika/misenomika.github.io"
          repoID           = "R_kgDOS9B30g"

          category         = "Announcements"
          categoryID       = "DIC_kwDOS9B30s4C_Zoi"

          mapping          = "pathname"

          reactionsEnabled = 1
          emitMetadata     = 0

          inputPosition    = "top"

          lang             = "en"

          strict           = 1

          loading          = "eager"

          lightTheme       = "light"
          darkTheme        = "dark_dimmed"
    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
